const mongoose = require('mongoose');

// The immutable, generated artifact — what the employee sees and what gets
// emailed. Payroll generation only ever CREATES a new Payslip; it is never
// edited after creation. If a mistake needs correcting after generation, a
// new Payslip is created with an incremented `version` and the old one is
// flipped to status:'Superseded' — the original numbers stay in the
// database untouched, satisfying "previous payslips are never changed".
const payslipSchema = new mongoose.Schema(
  {
    employeeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Employee',
      required: true,
      index: true
    },
    payrollRunId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'PayrollRun',
      required: true
    },
    month: { type: Number, required: true, min: 1, max: 12 },
    year: { type: Number, required: true },
    version: { type: Number, default: 1 },
    status: {
      type: String,
      enum: ['Active', 'Superseded'],
      default: 'Active'
    },

    // Frozen at generation time so later profile edits (name change,
    // designation change, etc.) never rewrite a historical payslip.
    employeeSnapshot: {
      name: String,
      employeeId: String,
      designation: String,
      department: String,
      joinDate: Date
    },

    earnings: {
      basic: Number, hra: Number, specialAllowance: Number, conveyance: Number,
      medicalAllowance: Number, otherAllowances: Number,
      bonus: Number, incentive: Number, reimbursement: Number, arrears: Number
    },
    deductions: {
      lopDeduction: Number, pf: Number, professionalTax: Number, tds: Number,
      otherDeductions: Number, otherDeductionsReason: String
    },
    attendanceSummary: {
      totalDaysInMonth: Number, presentDays: Number, paidLeaveDays: Number, lopDays: Number
    },

    grossEarnings: Number,
    totalDeductions: Number,
    netPay: Number,

    generatedAt: { type: Date, default: Date.now },
    generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'Admin', default: null }, // null = auto-generated by cron
    sentAt: Date,
    emailStatus: { type: String, enum: ['NotSent', 'Sent', 'Failed'], default: 'NotSent' },

    pdfUrl: String
  },
  { timestamps: true }
);

payslipSchema.index({ employeeId: 1, month: 1, year: 1, version: 1 }, { unique: true });

module.exports = mongoose.model('Payslip', payslipSchema);
